import Head from 'next/head'
import Footer from './components/Footer'
import Header from './components/Header'
import Intro from './components/Intro'
import Outro from './components/Outro'
import Shortener from './components/Shortener'
import Statistics from './components/Statistics'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"/>
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin = "true"/>
				<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet"/>
				<link href="https://fonts.googleapis.com/css2?family=Space+Mono&display=swap" rel="stylesheet"/>
			</Head>
			<Header />
			<Intro />
			<Shortener />
			<Statistics />
			<Outro />
			{/* <Footer /> */}
		</div>
	)
}
